### ISSUE TITLE
[无法编译] At least one <template> or <script> is required in a single file component.

### ISSUE THREAD

**Issue by YidaozhanYa** [GuMengYu/music-you#22]
**Describe the bug**
```
[vite:vue] At least one <template> or <script> is required in a single file component.
file: /home/yidaozhan/music-you/packages/renderer/src/pages/search/more.vue
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [SyntaxError]: At least one <template> or <script> is required in a single file component.
    at Object.parse (/home/yidaozhan/music-you/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:5245:21)
    at createDescriptor (/home/yidaozhan/music-you/node_modules/@vitejs/plugin-vue/dist/index.js:4005:43)
    at transformMain (/home/yidaozhan/music-you/node_modules/@vitejs/plugin-vue/dist/index.js:4350:34)
    at Object.transform (/home/yidaozhan/music-you/node_modules/@vitejs/plugin-vue/dist/index.js:4739:16)
    at /home/yidaozhan/music-you/node_modules/rollup/dist/shared/rollup.js:22826:37 {
  id: '/home/yidaozhan/music-you/packages/renderer/src/pages/search/more.vue',
  plugin: 'vite:vue',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  watchFiles: [
    '/home/yidaozhan/music-you/packages/renderer/index.html',
    'vite/modulepreload-polyfill',
```
...

**To Reproduce**
`pnpm run electron:build:linux`

**Desktop (please complete the following information):**
Node.js Linux v16.18.0

**Comment by GuMengYu** [comment]
packages/renderer/src/pages/search/more.vue 这是个无用文件，你可以先删掉

**Comment by YidaozhanYa** [comment]
这个文件在未来会不会被删除？如果会删除那我就打包了 (

**Comment by YidaozhanYa** [comment]
master 分支编译成功
这个 SearchMore 似乎还没做好，先关掉了

**Comment by YidaozhanYa** [comment]
即使 checkout 到最新 release 的 bebf247a3fb173f839dd4c1899747db3634f85c9，也没法编译，还是有这个错误。
不过去除所有 SearchMore 之后，总算是跑起来了。

**Comment by YidaozhanYa** [comment]
Linux 已经 pr 了，不过你还需要先去除 SearchMore，或者把 SearchMore 写好才能发布

**Comment by GuMengYu** [comment]
#24

**Comment by YidaozhanYa** [comment]
不知道 Actions 里是用什么魔法编译的，我这边只能去掉 SearchMore 才能编译出来
